# Generated by Django 5.2.6 on 2025-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
