# Generated by Django 5.2.6 on 2025-11-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Papelería y Dispensadores', [('higienicos', 'Higiénicos'), ('toallas_papel', 'Toallas de papel'), ('servilletas', 'Servilletas'), ('panuelos', 'Pañuelos'), ('panos', 'Paños'), ('sabanillas', 'Sabanillas'), ('dispensadores', 'Dispensadores')]), ('Artículos de Aseo', [('contenedores', 'Contenedores'), ('basureros', 'Basureros'), ('articulos_limpieza', 'Artículos de limpieza'), ('aseo', 'Aseo')]), ('Productos Químicos', [('pisos', 'Pisos'), ('limpiadores', 'Limpiadores'), ('desodorante', 'Desodorante Ambiental'), ('automotriz', 'Automotriz'), ('lavanderia', 'Lavandería')]), ('Seguridad y Horeca', [('epp', 'Elementos de Protección Personal (EPP)'), ('horeca', 'HORECA (Hoteles, Restaurantes, Cafeterías)')])], default='limpiadores', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
    ]
