# Generated by Django 5.2.5 on 2025-11-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_pedido_total_alter_pedidoitem_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
