# Generated by Django 5.2.5 on 2025-11-30 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(default=0, verbose_name='Descuento (%)'),
        ),
    ]
