# Generated by Django 5.2.5 on 2025-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_factura_facturaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
